# docker compose -p my-rdbms-4 up -d
services:
    my-mysql-service:
        container_name: mysql-container-4
        image: mysql
        environment:
            MYSQL_DATABASE: shop-db
            MYSQL_ROOT_PASSWORD: secret-root
            MYSQL_USER: user-app
            MYSQL_PASSWORD: secret-app
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
            interval: 10s
            retries: 10