# docker compose -p my-rdbms-1 up -d
services:
    my-mysql-service:
        container_name: mysql-container-1
        image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: secret-root
          MYSQL_USER: user-app
          MYSQL_PASSWORD: secret-app
        volumes:
          - ./mysql_data:/var/lib/mysql
        ports:
          - 3306:3306
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
          interval: 10s
          retries: 10